# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1D1E22)
$foreground = rgb(C6DCF5)
$color0 = rgb(434549)
$color1 = rgb(0D1725)
$color2 = rgb(101D2D)
$color3 = rgb(294667)
$color4 = rgb(354B6F)
$color5 = rgb(3F6999)
$color6 = rgb(4675AA)
$color7 = rgb(A6C5E8)
$color8 = rgb(748AA2)
$color9 = rgb(111F31)
$color10 = rgb(16273C)
$color11 = rgb(375E8A)
$color12 = rgb(466494)
$color13 = rgb(548CCC)
$color14 = rgb(5D9CE2)
$color15 = rgb(A6C5E8)
