# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(25242E)
$foreground = rgb(DCCEE7)
$color0 = rgb(4A4A55)
$color1 = rgb(0F193E)
$color2 = rgb(0F193E)
$color3 = rgb(151D43)
$color4 = rgb(3E2F9E)
$color5 = rgb(554373)
$color6 = rgb(74568C)
$color7 = rgb(C4B0D4)
$color8 = rgb(8A7B94)
$color9 = rgb(142153)
$color10 = rgb(142153)
$color11 = rgb(1C2659)
$color12 = rgb(523FD3)
$color13 = rgb(71599A)
$color14 = rgb(9B72BA)
$color15 = rgb(C4B0D4)
