# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #DCCEE7
background         #25242E
cursor             #78779D

active_tab_foreground     #25242E
active_tab_background     #DCCEE7
inactive_tab_foreground   #DCCEE7
inactive_tab_background   #25242E

active_border_color   #DCCEE7
inactive_border_color #25242E
bell_border_color     #0F193E

color0      #4A4A55
color1		#0F193E
color2		#0F193E
color3		#151D43
color4		#3E2F9E
color5		#554373
color6		#74568C
color7		#C4B0D4
color8		#8A7B94
color9		#142153
color10		#142153
color11		#1C2659
color12		#523FD3
color13		#71599A
color14		#9B72BA
color15		#C4B0D4
