$primary_paletteKeyColor = 93689d
$secondary_paletteKeyColor = 847185
$tertiary_paletteKeyColor = 9e6a65
$neutral_paletteKeyColor = 7c757b
$neutral_variant_paletteKeyColor = 7e747d
$background = 161217
$onBackground = eae0e7
$surface = 161217
$surfaceDim = 161217
$surfaceBright = 3d373d
$surfaceContainerLowest = 110d12
$surfaceContainerLow = 1f1a1f
$surfaceContainer = 231e23
$surfaceContainerHigh = 2e282e
$surfaceContainerHighest = 393339
$onSurface = eae0e7
$surfaceVariant = 4c444c
$onSurfaceVariant = cfc3cd
$inverseSurface = eae0e7
$inverseOnSurface = 342f34
$outline = 988e97
$outlineVariant = 4c444c
$shadow = 000000
$scrim = 000000
$surfaceTint = e7b6f0
$primary = e7b6f0
$onPrimary = 462151
$primaryContainer = 5f3869
$onPrimaryContainer = fbd7ff
$inversePrimary = 784f82
$secondary = d6c0d6
$onSecondary = 3a2b3d
$secondaryContainer = 514154
$onSecondaryContainer = f2dbf3
$tertiary = f5b7b1
$onTertiary = 4c2522
$tertiaryContainer = ba837e
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = fbd7ff
$primaryFixedDim = e7b6f0
$onPrimaryFixed = 2f0a3a
$onPrimaryFixedVariant = 5f3869
$secondaryFixed = f2dbf3
$secondaryFixedDim = d6c0d6
$onSecondaryFixed = 241727
$onSecondaryFixedVariant = 514154
$tertiaryFixed = ffdad6
$tertiaryFixedDim = f5b7b1
$onTertiaryFixed = 33110f
$onTertiaryFixedVariant = 673b37
$term0 = 353434
$term1 = ec4ae2
$term2 = ffbac2
$term3 = ffdded
$term4 = b1a3d6
$term5 = d495d5
$term6 = 9dceff
$term7 = e9d2dc
$term8 = af9ea6
$term9 = ff71f1
$term10 = ffd2d5
$term11 = fff0f5
$term12 = babfdd
$term13 = e5ade1
$term14 = ffd1c0
$term15 = ffffff
$rosewater = fceef5
$flamingo = f3dbec
$pink = fad0fb
$mauve = e4acf8
$red = e59ae2
$maroon = e2aedc
$peach = f8bce4
$yellow = ffecf3
$green = c8e3ff
$teal = dedcff
$sky = e3d4ff
$sapphire = d6bbff
$blue = d6acfc
$lavender = e5befe
$klink = 9b76c8
$klinkSelection = 9b76c8
$kvisited = ab65c1
$kvisitedSelection = ac64c0
$knegative = d155cd
$knegativeSelection = d255cd
$kneutral = fe7ae0
$kneutralSelection = ff7ae0
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = eae0e7
$subtext1 = cfc3cd
$subtext0 = 988e97
$overlay2 = 857b84
$overlay1 = 716870
$overlay0 = 5f575e
$surface2 = 4d464d
$surface1 = 3b363c
$surface0 = 282429
$base = 161217
$mantle = 161217
$crust = 151116
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
