[pyprland]

plugins = ["scratchpads", "magnify"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.ollama]
animation = "fromRight"
command = "kitty --class kitty-ollama -e ollama run minimax-m3:cloud"
class = "kitty-ollama"
size = "20% 90%"
